version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ingressos_db
    environment:
      POSTGRES_USER: ingressos_user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: ingressos_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: ingressos_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - 15672:15672  # interface de gerenciamento
      - 5672:5672    # porta de comunicação
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db_data:
  rabbitmq_data:
